# Generated by Django 4.1.6 on 2023-02-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='confirm_password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='country',
            field=models.CharField(choices=[(0, 'Italy'), (1, 'Norway'), (2, 'Turkey')], default='Please select your country', max_length=10),
        ),
        migrations.AlterField(
            model_name='custom',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
