# Generated by Django 4.1.6 on 2023-02-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_alter_custom_options_alter_custom_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='email_address'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
