# Generated by Django 4.1.6 on 2023-02-08 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_alter_custom_email_alter_custom_is_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='custom',
            managers=[
            ],
        ),
    ]
