# Generated by Django 4.1.6 on 2023-02-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_alter_custom_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='gender',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')], null=True),
        ),
    ]
