# Generated by Django 4.1.6 on 2023-02-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_alter_custom_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='country',
            field=models.CharField(choices=[(0, 'Italy'), (1, 'Norway'), (2, 'Turkey')], max_length=10),
        ),
        migrations.AlterField(
            model_name='custom',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
