# Generated by Django 4.1.6 on 2023-02-08 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_alter_custom_country_alter_custom_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom',
            name='country',
        ),
        migrations.RemoveField(
            model_name='custom',
            name='gender',
        ),
        migrations.AlterField(
            model_name='custom',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
