# Generated by Django 4.1.6 on 2023-02-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_remove_custom_country_remove_custom_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='email_address')),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('confirm_password', models.CharField(max_length=10, null=True)),
                ('date', models.DateField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')], max_length=10, null=True)),
                ('Country', models.CharField(choices=[(0, 'Italy'), (1, 'Norway'), (2, 'Turkey')], max_length=100, null=True)),
            ],
        ),
    ]
