# Generated by Django 4.1.6 on 2023-02-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Country',
            new_name='country',
        ),
    ]
